### ISSUE TITLE
[suggestion] Ability to set colour of coloured text plates by hand.

### ISSUE THREAD

**Issue by Ybaedbaenn** [ZengineerIO/factorio-evenmoretextplates#4]
Since the mod already has coloured text plates that can be any colour, it would be even better if their colour could be set manually to any value (like it is possible for vanilla trains).

That would allow, for example, to match the colour of the plates to colour of the resource being produced at a nearby factory (that the plates describe).

The option to match the player's colour could still be available in the mod's settings (on or off by default).

Feel free to ask for more details.

**Comment by Ybaedbaenn** [comment]
Since the mod isn't being maintained, I'm closing this.

**Comment by Ybaedbaenn** [comment]
Since the mod isn't being maintained, I'm closing this.

**Comment by ZengineerIO** [comment]
Hey, sorry I couldn't respond earlier, busy with life etc. Regarding your idea, that would mean a lot of UI coding and other trickery, which might go beyond my skills. If you are capable of doing that, I will happily review your PR and merge it if it all works out. For now I'll keep the idea in mind for the future, since I thought about that myself from time to time.
